<a href="https://colab.research.google.com/github/Jain-Dixon/MACHINE-LEARNING-WORKS/blob/main/AI_ML_INTERNSHIP_DAY_5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import cv2
import numpy as np
import matplotlib.pyplot as plt

In [ ]:
img = cv2.imread('/content/lena.png')
img = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)
plt.imshow(img)
plt.show()

error: OpenCV(4.13.0) /io/opencv/modules/imgproc/src/color.cpp:199: error: (-215:Assertion failed) !_src.empty() in function 'cvtColor'

In [ ]:
img.shape

In [ ]:
img[0,0]

In [ ]:
grey= cv2.cvtColor(img, cv2.COLOR_RGB2GRAY)
plt.imshow(grey, cmap='gray')
plt.axis('off')
plt.show()

In [ ]:
grey.shape

In [ ]:
edges = cv2.Canny(grey,100,200)
plt.imshow(edges, cmap='gray')
plt.axis('off')
plt.show()

In [ ]:
blur= cv2.GaussianBlur(grey,(25,25),0)
plt.imshow(blur, cmap='gray')
plt.title("Blurred")
plt.axis('off')
plt.show()

In [ ]:
from tensorflow.keras.datasets import mnist
from tensorflow.keras.utils import to_categorical
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import (Input,Dense, Conv2D, MaxPool2D, Flatten)
from tensorflow.keras.optimizers import SGD

In [ ]:
import tensorflow as tf
(x_train, y_train), (x_test, y_test) = tf.keras.datasets.mnist.load_data()

In [ ]:
x_train.shape

In [ ]:
y_train

In [ ]:
print(x_train[0])

In [ ]:
plt.imshow(x_train[0])

In [ ]:
plt.figure(figsize=(10,10  ))
for i in range(25):
  plt.subplot(5,5,i+1)
  plt.xticks([])
  plt.yticks([])
  plt.grid(False)
  plt.imshow(x_train[i], cmap='grey')
  plt.xlabel(y_train[i])

In [ ]:
x_train = x_train/255
x_test = x_test/255

In [ ]:
x_train[0]

In [ ]:
y_train[0]

In [ ]:
y_train=to_categorical(y_train)
y_test=to_categorical(y_test)

In [ ]:
y_train[0]

In [ ]:
model= Sequential()
model.add(Conv2D(32,(3,3),activation='relu',input_shape=(28,28,1)))
model.add(MaxPool2D((2,2)))
model.add(Flatten())
model.add(Dense(100,activation='relu'))
model.add(Dense(10,activation='softmax'))

In [ ]:
model.compile(optimizer='adam',loss='categorical_crossentropy',metrics=['accuracy'])

In [ ]:
model_mnist = model.fit(x_train,y_train,epochs=10,validation_data=(x_test,y_test))

In [ ]:
y_pred=model.predict(x_test)

In [ ]:
from google.colab import files

import io
from PIL import Image

In [ ]:
image_path='/content/number-five-5-hand-drawn-with-dry-brush.webp'
image_path

In [ ]:
new_image=Image.open(image_path).convert('L')
new_image=new_image.resize((28,28))
new_image=np.array(new_image)
new_image=new_image.reshape(1,28,28).astype('float32')/255

In [ ]:
prediction = model.predict(new_image)
predicted_digit=np.argmax(prediction)
print(f'predicted digit:v {predicted_digit}')

In [ ]:
import pandas as pd
from sklearn.feature_extraction.text import CountVectorizer

data=pd.read_csv('/content/spam.csv',encoding='Latin 1')

In [ ]:
data

,v1,v2,Unnamed: 2,Unnamed: 3,Unnamed: 4
0,ham,"Go until jurong point, crazy.. Available only in bugis n great world la e buffet... Cine there got amore wat...",NaN,NaN,NaN
1,ham,Ok lar... Joking wif u oni...,NaN,NaN,NaN
2,spam,Free entry in 2 a wkly comp to win FA Cup final tkts 21st May 2005. Text FA to 87121 to receive entry question(std txt rate)T&C's apply 08452810075over18's,NaN,NaN,NaN
3,ham,U dun say so early hor... U c already then say...,NaN,NaN,NaN
4,ham,"Nah I don't think he goes to usf, he lives around here though",NaN,NaN,NaN
...,...,...,...,...,...
5567,spam,"This is the 2nd time we have tried 2 contact u. U have won the å£750 Pound prize. 2 claim is easy, call 087187272008 NOW1! Only 10p per minute. BT-national-rate.",NaN,NaN,NaN
5568,ham,Will Ì_ b going to esplanade fr home?,NaN,NaN,NaN
5569,ham,"Pity, * was in mood for that. So...any other suggestions?",NaN,NaN,NaN
5570,ham,The guy did some bitching but I acted like i'd be interested in buying something else next week and he gave it to us for free,NaN,NaN,NaN
5571,ham,Rofl. Its true to its name,NaN,NaN,NaN

In [ ]:
pd.set_option('display.max_colwidth',None)
data.head()

,v1,v2,Unnamed: 2,Unnamed: 3,Unnamed: 4
0,ham,"Go until jurong point, crazy.. Available only in bugis n great world la e buffet... Cine there got amore wat...",NaN,NaN,NaN
1,ham,Ok lar... Joking wif u oni...,NaN,NaN,NaN
2,spam,Free entry in 2 a wkly comp to win FA Cup final tkts 21st May 2005. Text FA to 87121 to receive entry question(std txt rate)T&C's apply 08452810075over18's,NaN,NaN,NaN
3,ham,U dun say so early hor... U c already then say...,NaN,NaN,NaN
4,ham,"Nah I don't think he goes to usf, he lives around here though",NaN,NaN,NaN

In [ ]:
data=data[['v1','v2']]

In [ ]:
data.shape

In [ ]:
data['v1'].unique()

array(['ham', 'spam'], dtype=object)

In [ ]:
data['v1'].value_counts()

v1
ham     4825
spam     747
Name: count, dtype: int64

In [ ]:
data['v1']=data['v1'].map({'ham':0,'spam':1})

/tmp/ipykernel_14906/1170732115.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['v1']=data['v1'].map({'ham':0,'spam':1})

#data processing

In [ ]:
!pip  install gensim

Requirement already satisfied: gensim in /usr/local/lib/python3.12/dist-packages (4.4.0)
Requirement already satisfied: numpy>=1.18.5 in /usr/local/lib/python3.12/dist-packages (from gensim) (2.0.2)
Requirement already satisfied: scipy>=1.7.0 in /usr/local/lib/python3.12/dist-packages (from gensim) (1.16.3)
Requirement already satisfied: smart_open>=1.8.1 in /usr/local/lib/python3.12/dist-packages (from gensim) (7.6.1)
Requirement already satisfied: wrapt in /usr/local/lib/python3.12/dist-packages (from smart_open>=1.8.1->gensim) (2.2.1)

In [ ]:
import gensim
corpus=data['v2'].apply(lambda x:''.join(gensim.utils.simple_preprocess(x))).tolist()

In [ ]:
type(corpus)

list

In [ ]:
corpus

['gountiljurongpointcrazyavailableonlyinbugisgreatworldlabuffetcinetheregotamorewat',
 'oklarjokingwifoni',
 'freeentryinwklycomptowinfacupfinaltktsstmaytextfatotoreceiveentryquestionstdtxtrateapplyover',
 'dunsaysoearlyhoralreadythensay',
 'nahdonthinkhegoestousfhelivesaroundherethough',
 'freemsgheytheredarlingitbeenweeknowandnowordbacklikesomefunyouupforitstilltbokxxxstdchgstosendtorcv',
 'evenmybrotherisnotliketospeakwithmetheytreatmelikeaidspatent',
 'asperyourrequestmellemelleoruminnaminungintenurunguvettamhasbeensetasyourcallertuneforallcallerspresstocopyyourfriendscallertune',
 'winnerasvaluednetworkcustomeryouhavebeenselectedtoreceiveaprizerewardtoclaimcallclaimcodeklvalidhoursonly',
 'hadyourmobilemonthsormoreentitledtoupdatetothelatestcolourmobileswithcameraforfreecallthemobileupdatecofreeon',
 'gonnabehomesoonanddonwanttotalkaboutthisstuffanymoretonightvecriedenoughtoday',
 'sixchancestowincashfromtopoundstxtcshandsendtocostdaydaystsandcsapplyreplyhlinfo',
 'urgentyouhavewonweekfreemembershipinourprizejackpottxtthewordclaimtonowwwdbuknetlccltdpoboxldnwrw',
 'vebeensearchingfortherightwordstothankyouforthisbreatherpromisewonttakeyourhelpforgrantedandwillfulfilmypromiseyouhavebeenwonderfulandblessingatalltimes',
 'havedateonsundaywithwill',
 'touseyourcreditclickthewaplinkinthenexttxtmessageorclickherehttpwapcomqjkgighjjgcbl',
 'ohwatchinghere',
 'ehrememberhowspellhisnameyesdidhenaughtymakeuntilwet',
 'fineifthatåõsthewayfeelthatåõsthewayitsgota',
 'englandmacedoniadontmissthegoalsteamnewstxturnationalteamtoegenglandtotrywalesscotlandtxtì¼poboxoxwq',
 'isthatseriouslyhowyouspellhisname',
 'goingtotryformonthshahaonlyjoking',
 'soì_payfirstlarthenwhenisdastockcomin',
 'aftfinishmylunchthengostrdownlorardsmthlorfinishurlunchalready',
 'ffffffffffalrightnowaycanmeetupwithyousooner',
 'justforcedmyselftoeatslicereallynothungrythothissucksmarkisgettingworriedheknowssickwhenturndownpizzalol',
 'lolyouralwayssoconvincing',
 'didyoucatchthebusareyoufryinganeggdidyoumaketeaareyoueatingyourmomleftoverdinnerdoyoufeelmylove',
 'backampwerepackingthecarnowllletyouknowifthereroom',
 'ahhhworkvaguelyrememberthatwhatdoesitfeellikelol',
 'waitthatstillnotallthatclearwereyounotsureaboutmebeingsarcasticorthatthatwhydoesnwanttolivewithus',
 'yeahhegotinatandwasapologetichadfallenoutandshewasactinlikespoiltchildandhegotcaughtupinthattillbutwewongotherenotdoingtoobadlycheersyou',
 'tellmeanythingaboutyou',
 'forfearoffaintingwiththeofallthathouseworkyoujustdidquickhavecuppa',
 'thanksforyoursubscriptiontoringtoneukyourmobilewillbechargedmonthpleaseconfirmbyreplyingyesornoifyoureplynoyouwillnotbecharged',
 'yupokgohomelookatthetimingsthenmsgì_againxuhuigoingtolearnonndmaytoobutherlessonisatam',
 'oopsllletyouknowwhenmyroommatedone',
 'seetheletteronmycar',
 'anythinglordecide',
 'hellohowyouandhowdidsaturdaygowasjusttextingtoseeifyoudecidedtodoanythingtomonotthattryingtoinvitemyselforanything',
 'plsgoaheadwithwattsjustwantedtobesuredohavegreatweekendabiola',
 'didforgettotellyouwantyouneedyoucraveyoubutmostofallloveyoumysweetarabiansteedmmmmmmyummy',
 'rodgerburnsmsgwetriedtocallyoureyourreplytooursmsforfreenokiamobilefreecamcorderpleasecallnowfordeliverytomorrow',
 'whoareyouseeing',
 'greathopeyoulikeyourmanwellendowedamltgtinches',
 'nocallsmessagesmissedcalls',
 'didnyougethepimmunisationinnigeria',
 'fairenoughanythinggoingon',
 'yeahhopefullyiftylercandoitcouldmaybeaskaroundbit',
 'donknowhowstubbornamdidnevenwanttogotothehospitalkepttellingmarknotweaksuckerhospitalsareforweaksuckers',
 'whatyouthinkedaboutmefirsttimeyousawmeinclass',
 'gramusuallyrunslikeltgthalfeighthissmarterthoughandgetsyoualmostwholesecondgramforltgt',
 'fyihasrideearlytomorrowmorningbuthecrashingatourplacetonight',
 'wowneverrealizedthatyouweresoembarassedbyyouraccomodationsthoughtyoulikeditsincewasdoingthebestcouldandyoualwaysseemedsohappyaboutthecavesorrydidnanddonhavemoretogivesorryofferedsorryyourroomwassoembarassing',
 'smsacsptvthenewjerseydevilsandthedetroitredwingsplayicehockeycorrectorincorrectendreplyendsptv',
 'doyouknowwhatmallikasherawatdidyesterdayfindoutnowlturlgt',
 'congratsyearspecialcinemapassforisyourscallnowsuprmanmatrixstarwarsetcallfreebxipwepmdontmissout',
 'sorryllcalllaterinmeeting',
 'tellwhereyoureached',
 'yesgautiandsehwagoutofodiseries',
 'yourgonnahavetopickupburgerforyourselfonyourwayhomecanevenmovepainiskillingme',
 'hahahagoodjokegirlsaresituationseekers',
 'itspartofcheckingiq',
 'sorrymyroommatestookforeveritokifcomebynow',
 'oklardoublecheckwifdahairdresseralreadyhesaidwuncutshorthesaidwillcutuntillooknice',
 'asvaluedcustomerampleasedtoadviseyouthatfollowingrecentreviewofyourmobnoyouareawardedwithbonusprizecall',
 'todayissongdedicateddaywhichsongwilldedicateformesendthistoallurvaluablefrndsbutfirstrplyme',
 'urgenturawardedcomplimentarytriptoeurodisinctravacoentryortoclaimtxtdistomorefrmmoblsaj',
 'didyouhearaboutthenewdivorcebarbieitcomeswithallofkenstuff',
 'planetogiveonthismonthend',
 'wahluckymanthencansavemoneyhee',
 'finishedclasswhereareyou',
 'hibabeimathomenowwannadosomethingxx',
 'whereareyouhowdidyouperformed',
 'cancallmenow',
 'amwaitingmachancallmeonceyoufree',
 'thatscoolamgentlemanandwilltreatyouwithdignityandrespect',
 'likeyoupeoplesverymuchbutamveryshypa',
 'doesnotoperateafterltgtorwhat',
 'itsnotthesameherestilllookingforjobhowmuchdotaearnthere',
 'sorryllcalllater',
 'didyoucallmejustnowah',
 'okamonthewaytohomehihi',
 'youwillbeintheplaceofthatman',
 'yupnextstop',
 'callyoulaterdonhavenetworkifurgntsmsme',
 'forrealwhengettingonyoonlyneedmoreticketsandonemorejacketanddonealreadyusedallmymultis',
 'yesstartedtosendrequeststomakeitbutpaincamebacksobackinbeddoublecoinsatthefactorytoogottacashinallmynitros',
 'reallynotuptoitstilltonightbabe',
 'elakanoildownloadcomewenurfree',
 'yeahdodonstandtoclosethoyoullcatchsomething',
 'sorrytobepainisitokifwemeetanothernightspentlateafternoonincasualtyandthatmeanshavendoneanyofstuffmoroandthatincludesallmytimesheetsandthatsorry',
 'smileinpleasuresmileinpainsmilewhentroublepourslikerainsmilewhensumhurtssmilebecozsomeonestilllovestoseesmiling',
 'pleasecallourcustomerservicerepresentativeonbetweenampmasyouhavewonguaranteedcashorprize',
 'haventplanningtobuylatercheckalreadylidoonlygotshowinafternoonfinishworkalready',
 'yourfreeringtoneiswaitingtobecollectedsimplytextthepasswordmixtotoverifygetusherandbritneyfml',
 'watchingtelugumoviewatabt',
 'seewhenwefinishwehaveloadsofloanstopay',
 'hiwkbeenokonholsnowyesonforbitofrunforgotthathavehairdressersappointmentatfoursoneedtogethomeshowerbeforehanddoesthatcauseprobforham',
 'pleasedontextmeanymorehavenothingelsetosay',
 'okaynameurpriceaslongasitslegalwencanpickthemupaveamsxx',
 'stilllookingforcartobuyandhavenotgonethedrivingtestyet',
 'asperyourrequestmellemelleoruminnaminungintenurunguvettamhasbeensetasyourcallertuneforallcallerspresstocopyyourfriendscallertune',
 'wowyourerightdidnmeantodothatguessoncegaveuponbostonmenandchangedmysearchlocationtonycsomethingchangedcuzonmysigninpageitstillsaysboston',
 'ummamylifeandvavaummaloveyoulotdear',
 'thankslotforyourwishesonmybirthdaythanksyouformakingmybirthdaytrulymemorable',
 'aightllhityouupwhengetsomecash',
 'howwouldmyipaddresstestthatconsideringmycomputerisnminecraftserver',
 'knowgrumpyoldpeoplemymomwaslikeyoubetternotbelyingthenagainamalwaystheonetoplayjokes',
 'dontworryguesshebusy',
 'whatisthepluralofthenounresearch',
 'goingfordinnermsgyouafter',
 'okwifitcosliketrynewthingsbutscareddunlikemahcossaidnottooloud',
 'gentwearetryingtocontactyoulastweekendsdrawshowsthatyouwonprizeguaranteedcallclaimcodevalidhrsonlyppm',
 'wauropeninsentenceveryformalanywayfinetoojuztteatintoomuchputtinonweighthahasoanythinspecialhappened',
 'asenteredmycabinmypasaidhappydaybossfeltspecialsheaskdmelunchafterlunchsheinvitedmetoherapartmentwewentthere',
 'youarewinnerhavebeenspeciallyselectedreceiveorholidayflightsincspeaktoliveoperatorclaimmin',
 'goodoyeswemustspeakfridayeggpotatoratiofortortillaneeded',
 'hmmmyunclejustinformedmethathepayingtheschooldirectlysoplsbuyfood',
 'privateyouraccountstatementforshowsunredeemedbonuspointstoclaimcallidentifiercodeexpires',
 'urgentyourmobilenowasawardedbonuscallerprizeonthisisourfinaltrytocontactcallfromlandlineboxwrppm',
 'hereismynewaddressapplespairsallthatmalarky',
 'todaysvodanumbersendingareselectedtoreceiveawardifyouhavematchpleasecallquotingclaimcodestandardratesapp',
 'amgoingtosaomutodaywillbedoneonlyat',
 'ìïpredictwattimeì_llfinishbuying',
 'goodstuffwilldo',
 'justsothatyouknowyetundehasnsentmoneyyetjustsenthertextnottobothersendingsoitsoveryoudonthavetoinvolveyourselfinanythingshouldnhaveimposedanythingonyouinthefirstplacesoforthatapologise',
 'areyouthereinroom',
 'heygirlhowhopewellmeandelbakagainlongtimenogivemecallsumtimefromlucyxx',
 'howmuchdoesitcost',
 'home',
 'dearwillcalltmorrowplsaccomodate',
 'firstanswermyquestion',
 'sunshinequizwklywintopsonydvdplayerifknowwhichcountrythealgarveisintxtansrtosptyrone',
 'wantgetlaidtonightwantrealdogginglocationssentdirecturmobjointheuklargestdoggingnetworkbttxtinggraveltontecmsg',
 'onlyhafmsnityijuehotmailcom',
 'heisthereyoucallandmeethim',
 'nonowillcheckallroomsbeforactivities',
 'youllnotrcvanymoremsgsfromthechatsvcforfreehardcoreservicestextgotoifgetnothingmustageverifywithyrnetworktryagain',
 'gotlazytotypeforgotì_inlectsawpouchbutlikenotnice',
 'textmewhenyoureontheway',
 'sirwaitingforyourmail',
 'swtthoughtnvergettiredofdoinglittlethingslovablepersonscozsomtimesthoselittlethingsoccupybiggestpartintheirheartsgudni',
 'knowyouarecanyouplsopentheback',
 'yesseeyanotonthedot',
 'whatsthestaffnamewhoistakingclassforus',
 'freemsgwhyhavenyourepliedtomytextrandysexyfemaleandlivelocalluvtohearfromnetcollexltdpermsgreplystoptoend',
 'ummmawillcallaftercheckinourlifewillbeginfromqatarsoplsprayveryhard',
 'deletedmycontactthatwhy',
 'sindugotjobinbirlasoft',
 'thewineisflowingandhavenevering',
 'yupthkcineisbettercosnoneedgodownplazamah',
 'okurtypicalreply',
 'asperyourrequestmellemelleoruminnaminungintenurunguvettamhasbeensetasyourcallertuneforallcallerspresstocopyyourfriendscallertune',
 'youareeverywheredirtonthefloorthewindowsevenonmyshirtandsometimeswhenopenmymouthyouareallthatcomesflowingoutdreamofmyworldwithoutyouthenhalfmychoresareouttootimeofjoyformelotsoftvshowsllseebutguesslikeallthingsyoujustmustexistlikerainhailandmistandwhenmytimehereisdoneyouandbecomeone',
 'aaoooorightareyouatwork',
 'leavingmyhousenow',
 'hellomylovewhatareyoudoingdidyougettothatinterviewtodayareyouyouhappyareyoubeinggoodboydoyouthinkofmeareyoumissingme',
 'customerserviceannoncementyouhavenewyearsdeliverywaitingforyoupleasecallnowtoarrangedelivery',
 'youarewinnerhavebeenspeciallyselectedreceivecashorholidayflightsincspeaktoliveoperatorclaim',
 'keepyourselfsafeformebecauseneedyouandmissyoualreadyandenvyeveryonethatseeyouinreallife',
 'newcarandhouseformyparentshaveonlynewjobinhand',
 'soinlovewithyouexcitedeachdayspendwithyouyoumakemesohappy',
 'plsstopbootydeliousisinvitingyoutobeherfriendreplyyesornoseeherwwwsmsacbootydeliousstopsendstopfrndto',
 'bangbabesurorderisonthewayshouldreceiveservicemsgdownloadurcontentifdonotgotowapbangbtvonurmobileinternetservicemenu',
 'placeallurpointsonculturesmodulealready',
 'urgentwearetryingtocontactyoulastweekendsdrawshowsthatyouhavewonprizeguaranteedcallclaimcodevalidhrsonly',
 'hifrndwhichisbestwaytoavoidmissunderstdingwitourbelovedone',
 'greatescapefancythebridgebutneedsherlagerseeyoutomo',
 'yesitcompletelyinoutofformclarkalsoutterwaste',
 'sirneedaxisbankaccountnoandbankaddress',
 'hmmmthksuregottimetohopardyacangofreeabtmuzcalltodiscussliao',
 'whattimeyoucomingdownlater',
 'bloodyhellcantbelieveyouforgotmysurnamemrillgiveclueitsspanishandbeginswith',
 'wellgonnafinishmybathnowhavegoodfinenight',
 'letmeknowwhenyouvegotthemoneysocarloscanmakethecall',
 'stillgoingtothemall',
 'turnsoutmyfriendsarestayingforthewholeshowandwonbebacktilltgtsofeelfreetogoaheadandsmokethatltgtworth',
 'textherifshedoesntreplyletmeknowsocanhaveherlogin',
 'hiyoujustspoketomaneeshaweliketoknowifyouweresatisfiedwiththeexperiencereplytollfreewithyesorno',
 'youliftedmyhopeswiththeofferofmoneyaminneedespeciallywhentheendofthemonthapproachesandithurtsmystudyinganywayshavegrweekend',
 'lolnocantrustme',
 'okamgentlemanandwilltreatyouwithdignityandrespect',
 'hewillyouguysclose',
 'goingonnothinggreatbye',
 'hellohandsomeareyoufindingthatjobnotbeinglazyworkingtowardsgettingbackthatnetformummywheremyboytoynowdoeshemissme',
 'hahaawesomebethereinminute',
 'pleasecallourcustomerservicerepresentativeonfreephonebetweenampmasyouhavewonguaranteedcashorprize',
 'haveyougotxmasradiotimesifnotwillgetitnow',
 'jusreachedhomegobathefirstbutmysisusingnettellwhenshefinishes',
 'areyouuniqueenoughfindoutfromthaugustwwwareyouuniquecouk',
 'sorryvejoinedtheleagueofpeoplethatdontkeepintouchyoumeangreatdealtomeyouhavebeenfriendatalltimesevenatgreatpersonalcostdohavegreatweek',
 'hifinallycompletedthecourse',
 'itwillstoponitselfhoweversuggestshestayswithsomeonethatwillbeabletogiveorsforeverystool',
 'howareyoudoinghopeyouvesettledinforthenewschoolyearjustwishinyougrday',
 'gudmrngdearhavniceday',
 'didgotthatpersonsstory',
 'isyourhamsterdeadheysotmrmeetyouatpmorchardmrt',
 'hiitskatehowisyoureveninghopecanseeyoutomorrowforbitbuthavetobloodybabyjontettxtbackifcanxxx',
 'founditencltgtwhereyouat',
 'sentyoultgtbucks',
 'hellodarlinivefinishedcollegenowsotxtmewhenfinishifcanlovekatexxx',
 'youraccounthasbeenrefilledsuccessfullybyinrltdecimalgtyourkeralacircleprepaidaccountbalanceisrsltdecimalgtyourtransactionidiskrltgt',
 'goodmorningsleepingga',
 'callmealteratok',
 'ìïsayuntillikedatdunbuyericssonosocannotoredilar',
 'asenteredmycabinmypasaidhappydaybossfeltspecialsheaskdmelunchafterlunchsheinvitedmetoherapartmentwewentthere',
 'aightyodatsstraightdogg',
 'youpleasegiveusconnectiontodayitselfbeforeltdecimalgtorrefundthebill',
 'bothshootbigloadssogetready',
 'whatupbruvhopeyouhadgreatbreakdohaverewardingsemester',
 'homesowecanalwayschat',
 'goodstudywell',
 'yuphowì_noeleh',
 'soundsgreatareyouhomenow',
 'finallythematchheadingtowardsdrawasyourprediction',
 'tiredhavensleptwellthepastfewnights',
 'easyahsengotselectedmeansitsgood',
 'havetotakeexamwithmarch',
 'yeahyoushouldthinkyoucanuseyourgtatmnowtoregisternotsurebutifthereanywaycanhelpletmeknowbutwhenyoudobesureyouareready',
 'oknoprobtakeurtime',
 'thereisoscalledubanduwhichwillrunwithoutinstallinginharddiskyoucanusethatostocopytheimportantfilesinsystemandgiveittorepairshop',
 'sorryllcalllater',
 'saylehofcoursenothinghappenlarnotsayromanticjusbitonlylorthknitescenerynotsoniceleh',
 'newmobilesfrommustgotxtnokiatonocollectyourstodayfromonlywwwtcbizoptoutgbpmtmsg',
 'wouldreallyappreciateifyoucallmejustneedsomeonetotalkto',
 'willmeeturdreampartnersoonisurcareeroffflyngstartfindoutfreetxthorofollowedbyurstarsignhoroaries',
 'heycompanyelamapomudyadhu',
 'lifeismorestrictthanteacherbcozteacherteacheslessonampthenconductsexambutlifefirstconductsexamampthenteacheslessonshappymorning',
 'deargoodmorningnowonlyamup',
 'getdowningandhipuramandwalktocrosscutroadrightsideltgtstreetroadandturnatfirstright',
 'dearwearegoingtoourrubberplace',
 'sorrybatterydiedyeahhere',
 'yesheretvisalwaysavailableinworkplace',
 'textmeetsomeonesexytodaycanfinddateorevenflirtitsuptojoinjustreplywithnameageegsammsgrecdthirtyeightpence',
 'haveprinteditohsoltgtcomeupstairs',
 'orillbelittlecloserlikeatthebusstoponthesamestreet',
 'whereareyouwhenwilyoureachhere',
 'newtheoryargumentwinssituationbutlosesthepersonsodontarguewithurfriendsjustkickthemampsayalwayscorrect',
 'havesecretadmirerwhoislookingmakecontactwithfindoutwhotheyrevealwhothinksursospecialcallon',
 'tomarrowfinalhearingonmylaptopcasesocant',
 'telmeaventdonesportsx',
 'okaynonojustshiningonthatwasmeanttobesigningbutthatsoundsbetter',
 'althoughtolddatintobaigfacewatchesnowbutreallylikewatchgavecositfrthanxeverythingdatvedonetodaytouched',
 'donrememberthatoldcommercial',
 'toolatesaidhavethewebsitedidnhaveordonthavetheslippers',
 'askedyoutocallhimnowok',
 'kalliswontbatinndinnings',
 'itdidntworkagainohokgoodnightthenllfixandhaveitreadybythetimeyouwakeupyouareverydearlymissedhavegoodnightsleep',
 'congratulationsurawardedofcdvouchersorgiftguaranteedfreeentrywklydrawtxtmusictotncswwwldewcomwinppmxage',
 'ranjithcaldrpddeerajanddeepakminhold',
 'wenurlovablebcumsangrywiddnttakeitseriouslycozbeingangryismostchildishtruewayofshowingdeepaffectioncareluvkettodamandahavenicedayda',
 'whatyoudoinghowareyou',
 'upswhichisdaysalsoandtheshippingcompanythattakeswkstheotherwayisuspswhichtakesweekbutwhenitgetstolagyoumayhavetobribeniposttogetyourstuff',
 'backlemmeknowwhenyoureready',
 'donnecessarilyexpectittobedonebeforeyougetbackthoughbecausejustnowheadinout',
 'mmmsoyummybabenicejolttothesuzy',
 'whereareyouloverneedyou',
 'wetriedtocontactyoureyourreplytoourofferofvideohandsetanytimenetworksminsunlimitedtextcamcorderreplyorcallnow',
 'parkednexttominiwhenareyoucomingintodaydoyouthink',
 'yup',
 'anywaygoingshoppingonmyownnowcosmysisnotdoneyetdundisturbliao',
 'mynoinlutonringmeifuraround',
 'heyamreallyhornywanttochatorseemenakedtexthottotextchargedatpmtounsubscribetextstop',
 'whyyoudintcomewithus',
 'samewanaplantripsometmethen',
 'notsureyetstilltryingtogetholdofhim',
 'urringtoneservicehaschangedfreecreditsgotoclubmobilescomtochoosecontentnowstoptxtclubstoptowkclubpoboxmkwt',
 'theevojusthadtodownloadflashjealous',
 'ringtoneclubgettheuksingleschartonyourmobileeachweekandchooseanytopqualityringtonethismessageisfreeofcharge',
 'cometomuweresortingoutournarcoticssituation',
 'nighthasendedforanotherdaymorninghascomeinspecialwaymayyousmilelikethesunnyraysandleavesyourworriesatthebluebluebay',
 'hmvbonusspecialpoundsofgenuinehmvvoucherstobewonjustanswereasyquestionsplaynowsendhmvtomoreinfowwwpercentrealcom',
 'usfguessmightaswelltakecar',
 'noobjectionmybfnotcoming',
 'thanx',
 'tellrobtomackhisgfinthetheater',
 'awesomellseeyouinbit',
 'justsentitsowhattypeoffooddoyoulike',
 'alldoneallhandedincelebrationsinfullswingyet',
 'yougotcalledtool',
 'wenmisssomeone',
 'okaskedformoneyhowfar',
 'okie',
 'yeahthinkmyusualguystillpassedoutfromlastnightifyougetaholdofanybodyletmeknowandllthrowdown',
 'mightcomebytonightthenifmyclassletsoutearly',
 'ok',
 'hibabyimcruisinwithmygirlfriendwhatupgivemecallinandhourathomeifthatsalrightorfonemeonthisfonenowlovejennyxxx',
 'mylifemeanslottomenotbecauselovemylifebutbecauselovethepeopleinmylifetheworldcallsthemfriendscallthemmyworldge',
 'dearshallmailtonitebusyinthestreetshallupdateyoutonitethingsarelookingokvarunnathuedukkukayeerakshaollubutgoodoneinrealsense',
 'heyyoutoldyournametogauthamah',
 'haffoundhimfeelsostupiddacamwasworking',
 'oopsgotthatbit',
 'areyouthismuchbuzy',
 'accidentallydeletedthemessageresendplease',
 'mobilecustomeryoumaynowclaimyourfreecameraphoneupgradepaygosimcardforyourloyaltycallonofferendsthfebapply',
 'unlessitsituationwhereyougogurlwouldbemoreappropriate',
 'hurtmeteasememakemecrybutintheendofmylifewhendieplzkeeponeroseonmygraveandsaystupidmisshavenicedaybslvyl',
 'cantpickthephonerightnowplssendmessage',
 'needcoffeeruntomocanbelieveitthattimeofweekalready',
 'awesomerememberthelasttimewegotsomebodyhighforthefirsttimewithdiesel',
 'shitthatisreallyshockingandscarycantimagineforseconddefupfornightoutdothinkthereissomewherecouldcrashfornightsaveontaxi',
 'ohandbythewayyoudohavemorefoodinyourfridgewanttogooutformealtonight',
 'heiswomdarfullactor',
 'smsacblinddateroddsisfromaberdeenunitedkingdomcheckhimouthttpimgsmsacicmbcktznoblinddatessendhide',
 'yupfromwhatrembthinkshouldbecanbook',
 'josaskifwanameetup',
 'lolyesourfriendshipishangingonthreadcausewonbuystuff',
 'themobcheckoutournewestselectionofcontentgamestonesgossipbabesandsportkeepyourmobilefitandfunkytextwapto',
 'wherearethegaragekeystheyarenonthebookshelf',

#Bag-of-words

In [ ]:
from sklearn.feature_extraction.text import CountVectorizer
cv=CountVectorizer(ngram_range=(1,2))
traindata=cv.fit_transform(corpus)
x=traindata
y=data['v1']

In [ ]:
corpus = [

          "data science is an overlap between arts an science",
          'generally arts and graduates are right-brained and science graduates are left-brained'

]

In [ ]:
def vectorizer_text(corpus):
  bow_model = CountVectorizer()
  dense_vec= bow_model.fit_transform(corpus).todense()
  bow_df=pd.DataFrame(dense_vec)
  bow_df.columns=sorted(bow_model.vocabulary_)
  return bow_df

In [ ]:
df_bow=vectorizer_text(corpus)
df_bow

,an,and,are,arts,between,brained,data,generally,graduates,is,left,overlap,right,science
0,2,0,0,1,1,0,1,0,0,1,0,1,0,2
1,0,2,2,1,0,2,0,1,2,0,1,0,1,1

In [ ]:
x

<Compressed Sparse Row sparse matrix of dtype 'int64'
	with 5567 stored elements and shape (5572, 5075)>

In [ ]:
from sklearn.ensemble import RandomForestClassifier
clf=RandomForestClassifier(n_estimators=100)
clf.fit(x,y)

RandomForestClassifier()

In [ ]:
from sklearn import metrics
y_pred=clf.predict(x)
metrics.accuracy_score(y,y_pred)

0.9998205312275664

In [ ]:
def find_spam(input):
  input=cv.transform(input)
  prediction=clf.predict(input)
  if prediction==0:
    print('message is ham')
  if prediction==1:
    print('message is spam')

In [ ]:
input=["gladwin lottery adichu."]
find_spam(input)

message is ham

#TF_IDF

In [ ]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [ ]:
def vectorizer_tfidf(corpus):
  tfidf_model = TfidfVectorizer()
  vector_list= tfidf_model.fit_transform(corpus).todense()
  tfidf_df=pd.DataFrame(vector_list)
  tfidf_df.columns=sorted(tfidf_model.vocabulary_)
  return tfidf_df

In [ ]:
df1=vectorizer_tfidf(corpus)
df1

,an,and,are,arts,between,brained,data,generally,graduates,is,left,overlap,right,science
0,0.616298,0.000000,0.000000,0.219250,0.308149,0.000000,0.308149,0.000000,0.000000,0.308149,0.000000,0.308149,0.000000,0.438501
1,0.000000,0.447074,0.447074,0.159048,0.000000,0.447074,0.000000,0.223537,0.447074,0.000000,0.223537,0.000000,0.223537,0.159048